#!/usr/bin/env bash

#DISTRO="$(lsb_release -i | cut -f 2-)"
DISTRO="Arch"

if [ $DISTRO != "Arch" ]; then
	echo "Bruh"
	exit 0
fi

sudo pacman -S --noconfirm --needed nwg-look nwg-displays ghostty hyprshot swaync libnotify hypridle zsh fzf hyprlock xdg-desktop-portal-gtk xdg-desktop-portal-hyprland gnome-keyring seahorse swww cliphist brightnessctl neovim thunderbird ripgrep fcitx5 fcitx5-configtool fcitx5-gtk fcitx5-mozc fcitx5-qt mpv mplayer rofi rofi-calc base-devel
sudo pacman -S --noconfirm --needed waybar ttf-font-awesome ttf-nerd-fonts-symbols ttf-cascadia-code ttf-cascadia-code-nerd adobe-source-han-sans-jp-fonts otf-ipafont noto-fonts-cjk noto-fonts-emoji pipewire pipewire-pulse pavucontrol gamescope
sudo pacman -S --noconfirm --needed pulseaudio pipewire-pulse wireplumber tlp

#rm -rf ~/.config/hypr
rm -rf ~/.config/waybar

if ! type "yay" >/dev/null; then
	git clone https://aur.archlinux.org/yay.git ~/Downloads/yay
	cd ~/Downloads/yay
	makepkg -si
fi


yay -S visual-studio-code-bin matugen-bin aurutils pacman-contrib python-pywal python-pywalfox swayimg spotify spicetify-cli tlpui wl-color-picker discord 1password  --noconfirm --needed

sudo chmod a+wr /opt/spotify
sudo chmod a+wr /opt/spotify/Apps -R
spicetify backup apply
spicetify config current_theme Brett
spicetify apply
