#!/usr/bin/env bash

sudo apt install pulseaudio ripgrep fd-find color-picker -y

# fuck off, why do i need snapd for zig
# source https://linuxcapable.com/how-to-install-and-enable-snap-on-linux-mint/
# probably shouldn't have deleted the file already, b/c i can't restore it now :|
sudo mv /etc/apt/preferences.d/nosnap.pref /etc/apt/preferences.d/nosnap.backup
sudo apt update
sudo apt install zsh llvm liblld-dev clang libclang-dev snapd -y
sudo systemctl enable --now snapd.service
if ! [ -d "${HOME}/.fzf" ]; then
	git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
	~/.fzf/install
fi
#if ! type "zig" > /dev/null; then
#sudo apt install -y snap
#sudo systemctl enable --now snapd.service
#snap install ghostty --classic --beta
#sudo apt remove snapd -y
#wget https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz -P $HOME/Downloads -nc
#tar xf $HOME/Downloads/zig-linux-x86_64-0.13.0.tar.xz -C ~/Downloads/
#git clone -b 0.14.x https://github.com/ziglang/zig $HOME/Downloads/zig
#cd $HOME/Downloads/zig
#mkdir build
#cd build
#cmake ..
#make install
#fi

#install libre wolf
if ! type "librewolf" >/dev/null; then
	sudo apt install extrepo -y && sudo extrepo enable librewolf && sudo apt update && sudo apt install librewolf -y
fi

if ! type "ghostty" >/dev/null; then
	snap install ghostty --classic --beta
fi
sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /snap/bin/ghostty 50
#git clone https://github.com/ghostty-org/ghostty $HOME/Downloads/ghostty
#cd $HOME/Downloads/ghostty
#zig build -Doptimize=ReleaseFast

if ! type "rofi" > /dev/null; then
	sudo apt install rofi-dev qalc meson -y
	git clone https://github.com/svenstaro/rofi-calc.git ~/Downloads/rofi-calc
	pushd ~/Downloads/rofi-calc
	meson setup build
	meson compile -C build/
fi
