#!/usr/bin/env bash

git config --global user.email "brett@brett.brett"
git config --global user.name "brett"

sudo pacman -S --noconfirm --needed firefox nwg-look ghostty hyprshot swaync libnotify hypridle zsh fzf hyprlock hyprpaper
sudo pacman -S --noconfirm --needed waybar ttf-font-awesome ttf-nerd-fonts-symbols ttf-cascadia-code
sudo pacman -S --noconfirm --needed pulseaudio easyeffects

#rm -rf ~/.config/hypr
rm -rf ~/.config/waybar
rm -rf $HOME/.local/scripts
rm $HOME/.bash_profile
rm $HOME/.zshrc
rm $HOME/.zsh_profile
rm $HOME/.p10k.zsh

cp .config ~/ -r
cp .local/scripts $HOME/.local/scripts -r
cp .bash_profile $HOME/.bash_profile
cp .zshrc $HOME/.zshrc
cp .zsh_profile $HOME/.zsh_profile
cp .p10k.zsh $HOME/.p10k.zsh

hyprctl reload
