#!/usr/bin/env bash

if [[ ! $1 =~ ^(true|false|1|0|yes|no)$ ]]; then
  echo "im bad at sh"
  exit 1
fi

sudo pacman -S --noconfirm --needed nwg-look nwg-displays ghostty hyprshot swaync libnotify hypridle zsh fzf hyprlock xdg-desktop-portal-gtk xdg-desktop-portal-hyprland gnome-keyring seahorse swww cliphist brightnessctl neovim thunderbird ripgrep fcitx5 fcitx5-configtool fcitx5-gtk fcitx5-mozc fcitx5-qt mpv xclip mplayer rofi rofi-calc base-devel easyeffects lsp-plugins fd jellyfin-mpv-shim dnsutils python-pystray mokutil fftw alsa-lib iniparser pkgconf cava
sudo pacman -S --noconfirm --needed waybar ttf-font-awesome ttf-nerd-fonts-symbols ttf-cascadia-code ttf-cascadia-code-nerd adobe-source-han-sans-jp-fonts otf-ipafont noto-fonts-cjk noto-fonts-emoji pavucontrol
sudo pacman -S --noconfirm --needed pipewire-pulse wireplumber tlp archlinux-xdg-menu
# to get the "open with application" menu to show applications
# FIXME: i don't think this works lol
XDG_MENU_PREFIX=arch- kbuildsycoca6

#rm -rf ~/.config/hypr
rm -rf ~/.config/waybar

if ! type "yay" >/dev/null; then
  git clone https://aur.archlinux.org/yay.git ~/Downloads/yay
  cd ~/Downloads/yay
  makepkg -si --noconfirm --needed
fi

# FIXME: idk how to check if this was already installed or not
# if ! type "deepfilternet" >/dev/null; then
if [[ $1 == true ]]; then
  git clone https://aur.archlinux.org/deepfilternet-git.git ~/Downloads/deepfilternet
  cd ~/Downloads/deepfilternet
  makepkg -si --noconfirm --needed
fi

yay -S visual-studio-code-bin matugen-bin aurutils pacman-contrib python-pywal python-pywalfox swayimg spotify spicetify-cli tlpui wl-color-picker discord 1password xwaylandvideobridge ark minecraft-launcher shim-signed hyprpolkitagent hyprpicker --noconfirm --needed
# install stuff for https://github.com/GNOME/gnome-network-displays
# TODO: something about the install may not work by default. im not sure what i did to get it working.
# The dummy display just didn't work for me.
yay -S gnome-network-displays ffmpeg dnsmasq xdg-desktop-portal-gnome gst-plugins-good gst-plugin-pipewire libva-mesa-driver gstreamer-vaapi faac wpa_suppliecant openh264 --noconfirm --needed

sudo chmod a+wr /opt/spotify
sudo chmod a+wr /opt/spotify/Apps -R
spicetify backup apply
spicetify config current_theme Brett
spicetify update
