[config]
reload_apps = true

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
# it's updating without the below hook
#post_hook = 'pkill -SIGUSR2 waybar'

[templates.ghostty]
input_path = './templates/ghostty'
output_path = "~/.config/ghostty/themes/matugen"
# There isn't a way to reload this damn config without just using ctrl+shit+, (until the next release (maybe))
#post_hook = "kill -SIGUSR2 $(pidof ghostty)"

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock-colors.conf'
output_path = '~/.config/hypr/hyprlock-colors.conf'

[templates.swaync]
input_path = '~/.config/matugen/templates/swaync-colors.css'
output_path = '~/.config/swaync/swaync-colors.css'
post_hook = 'swaync-client -rs'

#[templates.gtk3]
#input_path = '~/.config/matugen/templates/gtk.css'
#output_path = '~/.config/gtk-3.0/gtk.css'

#[templates.gtk4]
#input_path = '~/.config/matugen/templates/gtk.css'
#output_path = '~/.config/gtk-4.0/gtk.css'

[templates.qt5]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/qt5ct-colors.conf'

[templates.qt6]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/qt6ct-colors.conf'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'
