#!/usr/bin/env bash

DISTRO="$(lsb_release -i | cut -f 2-)"

#include the same as below for any submodules when i add them

if [ $DISTRO == "Arch" ]; then
  pushd ~/personal/dev/
fi

git add .
git commit -m 'auto commit'
git push

if [ $DISTRO == "Arch" ]; then
  popd
fi
