#!/usr/bin/env bash

# Gamescope just hates me and everything i sit for...
# so i made this by stealing some of the bash script from scopebuddy from bazzite /bin/scopebuddy
# gamescope wouldn't enable hdr on my monitor or in game. It completly disabled the steam overlay. Adding "-e" just stopped the game from opening at all.

# how to use:
# Add "hdr-game-launch -- %command%" without quotations to the LAUNCH OPTIONS of any steam game that will work with HDR

PRE_COMMAND="hyprctl keyword monitor DP-1,preferred,0x0,1,bitdepth,10,cm,hdr"
POST_COMMAND="hyprctl keyword monitor DP-1,preferred,0x0,1,bitdepth,10"

gamescope_opts=""
command=""

# Split the args at -- into gamescope_opts and command
while [[ $# -gt 0 ]]; do
    if [ "${1:-}" == "--" ]; then
        shift
        # Add remaining args as individually double quoted args (should stop double quoting being a requirement)
        while [[ $# -gt 0 ]]; do
            # command variable has to be formated like this otherwise the %command% will not launch
            # shellcheck disable=SC2089
            command+=" \"$1\""
            shift
        done
        
        # Exit loop when done
        break
    fi
    # Add arg to gamescope_opts and go to next loop
    gamescope_opts+=" $1"
    shift
done

echo -e "$command" > "$HOME/personal/log.log"

post_command() {
	eval "$POST_COMMAND"
}
trap post_command EXIT
eval "$PRE_COMMAND"
# not sure if all of these variables are needed but im pissed off and this works
eval "PROTON_ENABLE_WAYLAND=1 ENABLE_HDR_WSI=1 DXVK_HDR=1 $command"
