#!/usr/bin/env bash

DISTRO="$(lsb_release -i | cut -f 2-)"

if [$DISTRO == "Arch"]; then
  sudo pacman -S zsh --noconfirm
elif [$DISTRO == "Mint]; then
  sudo apt install zsh -y
fi
hash -r
chsh -s $(which zsh)
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
